// import { useState } from "react";
import ReduxProvider from "@/lib/ReduxProvider";
import NavbarCustom from "../components/NavbarCustom";
import "./globals.scss";
import { Young_Serif, Pixelify_Sans } from "next/font/google";
// import localFont from 'next/font/local'

const inter = Young_Serif({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-young",
});
const pixel = Pixelify_Sans({
  subsets: ["latin"],
  variable: "--font-pixel",
});

export const metadata = {
  title: "title global",
  description: "Generated by create next app",
  icons: {
    icon: "/next.svg",
  },
};

// const myfont = localFont({src : './'})

export default function RootLayout({ children }) {
  // const [count, setCount] = useState(0);

  return (
    <html lang="en">
      <ReduxProvider>
        <body className={`${inter.variable}  ${pixel.variable}`}>
          <NavbarCustom />
          <main>{children}</main>
        </body>
      </ReduxProvider>
    </html>
  );
}
