// import { useState } from "react";
import NavbarCustom from "../components/NavbarCustom";
import "./globals.scss";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "title global",
  description: "Generated by create next app",
  icons: {
    icon: "/next.svg",
  },
};

export default function RootLayout({ children }) {
  // const [count, setCount] = useState(0);

  return (
    <html lang="en">
      <body className={inter.className}>
        <NavbarCustom />
        {/* <h1>LAYOUT STATE {count}</h1>
        <button
          className="bg-green-400 p-2"
          onClick={() => setCount((v) => v + 1)}
        >
          klik layoutstate
        </button> */}
        <main>{children}</main>
      </body>
    </html>
  );
}
