"use client";
import { useState } from "react";
import NavbarCustom from "./NavbarCustom";
import "./globals.scss";
import { Inter } from "next/font/google";
import { usePathname } from "next/navigation";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

const disableRoute = ["/login", "/register"];

export default function RootLayout({ children }) {
  const [count, setCount] = useState(0);
  const pathname = usePathname();
  return (
    <html lang="en">
      <body className={inter.className}>
        {!disableRoute.includes(pathname) && <NavbarCustom />}
        {/* <h1>LAYOUT STATE {count}</h1>
        <button
          className="bg-green-400 p-2"
          onClick={() => setCount((v) => v + 1)}
        >
          klik layoutstate
        </button> */}
        <main>{children}</main>
      </body>
    </html>
  );
}
